### ISSUE TITLE
integrating crypto-pouch

### ISSUE THREAD

**Issue by pkojchevski** [colinskow/superlogin-demo#12]

**Comment by delkant** [comment]
Hello, is this the reason why the demo is not working?

I am getting this error: 

```
crypto.js:635
    throw new TypeError(
    ^

TypeError: The "digest" argument is required and must not be undefined
    at pbkdf2 (crypto.js:635:11)
    at Object.exports.pbkdf2 (crypto.js:623:10)
    at RandomBytes.ondone (/srv/superlogin-demo/node_modules/couch-pwd/index.js:55:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! superlogin-demo@0.2.0 start: `node ./server/bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the superlogin-demo@0.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by delkant** [comment]
The issue I was facing was happening on the server side.

https://github.com/colinskow/superlogin/issues/64 

Issue was fixed after replacing the couch-pwd/index.js for https://github.com/zemirco/couch-pwd/blob/master/index.js
